### ISSUE TITLE
deploy-ert.configure-ert attemps to configure properties that don't exist - install on GCP

### ISSUE THREAD

**Issue by dewoods** [pivotal-cf/pcf-pipelines#141]
I am attempting to run the GCP PCF pipeline in Concourse.  The configure-ert task of the deploy-ert job fails when attempting to set properties with the following error message:

```
==============================================================================================
Deploying ERT @ https://opsman.*** ...
==============================================================================================
==============================================================================================
Found ERT Deployment with guid of cf-58937bd350a351b69366
==============================================================================================
==============================================================================================
Setting Availability Zones & Networks for: cf-58937bd350a351b69366
==============================================================================================
{}
==============================================================================================
Setting Properties for: cf-58937bd350a351b69366
==============================================================================================
ERROR
stdout:n
{
  "errors": {
    ".properties.system_database.external.locket_username": [
      "is not a property"
    ],
    ".properties.system_database.external.locket_password": [
      "is not a property"
    ],
    ".properties.system_database.external.silk_username": [
      "is not a property"
    ],
    ".properties.system_database.external.silk_password": [
      "is not a property"
    ],
    ".properties.uaa_database": [
      "Non-configurable properties cannot be configured."
    ],
    "base": [
      "undefined method `find_option_property_with_identifier' for #\u003cPersistence::Models::Property identifier=\"uaa_database\"\u003e"
    ]
  }
}

stderr:n
Status: 500 Internal Server Error
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 23:07:05 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 29959e2c-f108-4ee8-8ab9-57f40d64dc3a
X-Runtime: 0.467416
X-Xss-Protection: 1; mode=block
```
I can look at `https://opsman.<url>/api/v0/staged/products/cf-58937bd350a351b69366/properties` and see that the above properties in the error message are not present.

All other steps of the pipeline succeed as expected.

Is there any way to prevent these properties from being sent in the API call to CF?

**Comment by ryanpei** [comment]
@dewoods thanks for sharing this with us. Which version of PCF were you running this pipeline against?

As of currently, the pipeline should only work with the 1.11 version of PCF.

**Comment by dewoods** [comment]
Thanks @ryanpei!  The PCF version is still set to 1.10 in install-pcf/gcp/params.yml in master.  I bumped it to 1.11 in my local copy and the pipeline worked as expected.  I guess that updating the version number was probably missed during commit 2d396a66e954e050bd35c3ce8ca75af3f89e3750.
